#--------------------------------------------------------------------------------
# Travis CI building configuration file for Linux Operating system
#                             created 2017-07-27
#--------------------------------------------------------------------------------

git:
  depth: 1

branches:
  only:
    - master

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qt5-qmake qtbase5-dev libqt5concurrent5 libqt5test5 qtbase5-dev-tools libqt5multimedia5-plugins libqt5multimediawidgets5
 - sudo apt-get install qt5-default qttools5-dev-tools

script:
 - qmake CONFIG-=debug CONFIG+=release
 - make

