#--------------------------------------------------------------------------------
# AppVeyor CI building configuration file for Microsoft Windows Operating system
#                             created 2016-08-09
#--------------------------------------------------------------------------------

version: 1.3.2.{build}

branches:
  only:  # whitelist
    - master

skip_tags: true

skip_commits:
    message: /Created.*\.(png|jpg|jpeg|bmp|gif|md)/       # Regex for matching commit message
    files:
        - '*.md'
        - 'LICENSE'
        - '.gitignore'

# Operating system (build VM template)
os: unstable

# clone directory
clone_folder: C:\_Repos\OPL3BankEditor
clone_depth:  3  # clone entire repository history if not defined
# Uncommend those two lines to enable RDP (which can be used to debug stuff and test built stuff)
# init:
# - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: new-item C:\temp-d -itemtype directory
  - ps: (new-object net.webclient).DownloadFile('http://wohlsoft.ru/docs/Software/QtBuilts/MinGW-6-3-x86-dw2.zip', 'C:\temp-d\MinGW-6-3-x86-dw2.zip');
  - ps: (new-object net.webclient).DownloadFile('http://wohlsoft.ru/docs/Software/QtBuilts/qt-4.4.3-mingw-6.3-win32-static-mini-release.7z', 'C:\temp-d\qt-4.4.3-mingw-6.3-win32-static-mini-release.7z');
  - ps: |
      Set-Alias sevenzip "C:\Program Files\7-Zip\7z.exe"
      sevenzip x C:\temp-d\MinGW-6-3-x86-dw2.zip -oC:\MinGW-6-3;
      sevenzip x C:\temp-d\qt-4.4.3-mingw-6.3-win32-static-mini-release.7z -oC:\Qt;
  - git submodule init
  - git submodule update
  - echo set QtDir=C:\Qt\4.4.3\bin>> _paths.bat
  - echo set MinGW=C:\MinGW-6-3\bin>> _paths.bat
  - echo set GitDir=C:\Program Files\Git\cmd>> _paths.bat

build_script:
  - build.bat win9x

artifacts:
  - path: opl3-bank-editor\opl3-bank-editor-dev-win9x.zip

deploy:
  - provider: Environment
    name: WohlnetFTP

